Document: cubar
Title: Debian cubar Manual
Author: <insert document author here>
Abstract: This manual describes what cubar is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cubar/cubar.sgml.gz

Format: postscript
Files: /usr/share/doc/cubar/cubar.ps.gz

Format: text
Files: /usr/share/doc/cubar/cubar.text.gz

Format: HTML
Index: /usr/share/doc/cubar/html/index.html
Files: /usr/share/doc/cubar/html/*.html
